config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars
  resources :vendors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "vendors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :vendor

  has_one_attached :image

  validates :name, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [ :show, :destroy, :edit, :update ]
  before_action :authenticate_user!
  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(set_params)

    if @car.save
      respond_to do |format|
        flash[:notice] = "Car successfully created."
        format.turbo_stream
      end
    else
      flash[:notice] = "Car creation failed."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @car.update(set_params)
      redirect_to car_path(@car)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy
    flash[:notice] = "Car has become deleted."
    redirect_to cars_path
  end

  def set_params
    params.expect(car: [ :name, :price, :vendor_id, :image ])
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [ :show, :destroy, :edit, :update ]
  before_action :authenticate_user!
  def index
    @vendors = Vendor.all
  end

  def show
  end

  def edit
  end

  def update
    if @vendor.update(set_params)
      redirect_to vendor_path(@vendor)
    else
      redirect_to :edit, status: :unprocessable_entity
    end
  end
  def new
    @vendor = Vendor.new
  end
  def create
    @vendor = Vendor.new(set_params)

    if @vendor.save
      respond_to do |format|
          flash[:notice] = "Vendor successfully created."
          format.turbo_stream
      end
    else
      flash[:notice] = "Vendor creation failed."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @vendor.destroy
    flash[:notice] = "Vendor has become deleted."
    redirect_to root_path
  end

  def set_vendor
    @vendor = Vendor.find(params[:id])
  end

  def set_params
    params.expect(vendor: [ :name, :country ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/cars/_car.html.erb
<tr>
    <td class="p-4 border-b border-blue-gray-50"><%= link_to car.name, car_path(car) %></td>
    <td class="p-4 border-b border-blue-gray-50"><%= car.price %> €</td>
</tr>

app/views/cars/_form.html.erb
<%= turbo_frame_tag "car_form" do %>
    <%= form_with(id: "car_form", model: @car) do |form| %>
        <% if @car.errors.any? %>
            <p><%= pluralize @car.errors.count, "error" %> prevented the operation</p>
            <% @car.errors.full_messages.each do |msg| %>
                <%= msg %>
            <% end %>
        <% end %>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :price %>
            <%= form.text_field :price %>
        </div>
        <div>
            <%= form.file_field :image %>
        </div>
        <div>
            <%= form.label :vendor_id %>
            <%= form.collection_select :vendor_id, Vendor.all, :id, :name, prompt: "Select a vendor"  %>
        </div>
        <%= form.submit class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <% end %>
    <%= link_to "Close form", :back, class: "font-bold" %>
<% end %>

app/views/cars/_link_form.html.erb
<%= turbo_frame_tag "car_form" do %>
    <%= link_to "Create new car", new_car_path, class: "font-bold" %>
<% end %>

app/views/cars/create.turbo_stream.erb
<%= turbo_stream.append "cars", partial: "cars/car", locals: {car: @car} %>
<%= turbo_stream.replace "car_form", partial: "cars/link_form" %>

app/views/cars/edit.html.erb
<h1 class="font-bold">Edit existing car</h1>
<%= render partial: "form", locals: {car: @car} %>

app/views/cars/index.html.erb
<h1 class="mb-4 text-4xl leading-none tracking-tight md:text-5xl lg:text-6xl dark:text-black">Available Cars</h1>
<%= render partial: "link_form" %>
<table class="w-full text-left table-auto min-w-max" id="cars">
    <tr>
        <th class="p-4 border-b border-blue-gray-100 bg-blue-gray-50">Name</th>
        <th class="p-4 border-b border-blue-gray-100 bg-blue-gray-50">Country</th>
    </tr>
<% @cars.each do |car| %>
    <%= render partial: "cars/car", locals: {car: car} %>
<% end %>
</table>

app/views/cars/new.html.erb
<h1 class="text-4xl">Create new car</h1>
<%= render partial: "form", locals: {car: @car} %>

app/views/cars/show.html.erb
<h1 class="text-4xl">Car details</h1>
<div>
    <%= button_to "Delete", car_path(@car), method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    <%= link_to "Edit", edit_car_path(@car) %>
</div>
<h2>Name: <%= @car.name %></h2>
<div>Country: <%= @car.price %> €</div>
<% if @car.image.attached? %>
<div>
    <%= image_tag(@car.image, style: "") %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Car Trader App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <h2 class="text-5xl">Car Trader-App <%= image_tag("placeholder.png", style: "display: inline; border-radius: 24px;") %></h2>
      <nav>
        <% if user_signed_in? %>
          <%= link_to "Vendors", root_path %> | 
          <%= link_to "Cars", cars_path %> | 
          <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </nav>
      <% flash.each do |name, msg| %>
        <ul>
          <li class="text-amber-900 font-bold"><%= msg %></li>
        </ul>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/vendors/_form.html.erb
<%= turbo_frame_tag "vendor_form" do %>
    <%= form_with model: vendor do |form| %>
        <% if vendor.errors.any? %>
            <p><%= pluralize vendor.errors.count, "error" %> prevented the operation</p>
            <% vendor.errors.full_messages.each do |msg| %>
                <%= msg %>
            <% end %>
        <% end %>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :country %>
            <%= form.text_field :country %>
        </div>
        <%= form.submit class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
    <% end %>
    <div>
        <%= link_to "Close form", vendors_path %>
    </div>
<% end %>

app/views/vendors/_link_form.html.erb
<%= turbo_frame_tag "vendor_form" do %>
    <%= link_to "Create new vendor", new_vendor_path %>
<% end %>

app/views/vendors/_vendor.html.erb
<tr>
    <td class="p-4 border-b border-blue-gray-50"><%= link_to vendor.name, vendor_path(vendor) %></td>
    <td class="p-4 border-b border-blue-gray-50"><%= vendor.country %></td>
</tr>

app/views/vendors/create.turbo_stream.erb
<%= turbo_stream.append "vendors", partial: "vendors/vendor", locals: {vendor: @vendor} %>
<%= turbo_stream.replace "vendor_form", partial: "vendors/link_form" %>

app/views/vendors/edit.html.erb
<h1 class="font-bold">Edit existing vendor</h1>
<%= render partial: "form", locals: {vendor: @vendor} %>

app/views/vendors/index.html.erb
<h1 class="mb-4 text-4xl leading-none tracking-tight md:text-5xl lg:text-6xl dark:text-black">Vendors</h1>
<%= render partial: "vendors/link_form" %>
<table class="w-full text-left table-auto min-w-max" id="vendors" >
    <tr>
        <th class="p-4 border-b border-blue-gray-100 bg-blue-gray-50">Name</th>
        <th class="p-4 border-b border-blue-gray-100 bg-blue-gray-50">Country</th>
    </tr>
<% @vendors.each do |vendor| %>
    <%= render partial: "vendors/vendor", locals: { vendor: vendor } %>
<% end %>
</table>

app/views/vendors/new.html.erb
<h1 class="font-bold">Create new vendor</h1>
<%= render partial: "form", locals: {vendor: @vendor} %>

app/views/vendors/show.html.erb
<h1 class="text-4xl">Vendor details</h1>
<div>
    <%= button_to "Delete", vendor_path(@vendor), method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    <%= link_to "Edit", edit_vendor_path(@vendor) %>
</div>
<h2>Name: <%= @vendor.name %></h2>
<div>Country: <%= @vendor.country %></div>